.TH SHOTWELL 1 "30 September 2013"
.SH NAME
\fBshotwell\fP \- a photo organizer for the GNOME desktop

.SH SYNOPSIS
.br
.B shotwell
[\fIOPTION\fR...] [\fIFILE\fR]

.SH DESCRIPTION
Shotwell is a photo organizer designed for the GNOME desktop. It allows you to
import photos from your camera, view and edit them, and share them with others.
.LP
.SH OPTIONS
.TP
\fB\-d, \-\-datadir=DIRECTORY\fR
Path to private data belonging to
.B shotwell
.TP
\fB\-\-no\-runtime\-monitoring\fR
Do not monitor library directory at runtime for changes.
.TP
\fB\-\-no\-startup\-progress\fR
Do not display startup progress meter.
.TP
\fB\-\-display=DISPLAY\fR
X display to use.
.TP
\fB\-V, \-\-version\fR
Output version information and exit.
.TP
\fB\-h, \-\-help\fR
Prints the command line options.

.SH BUGS
If you find a bug, please report it at http://redmine.yorba.org/projects/shotwell/issues/new.
